language: objective-c
osx_image: xcode7.3
before_install:
  - gem uninstall cocoapods
  - gem install cocoapods
  - pod install
script:
  xctool -workspace tripFinder.xcworkspace -scheme tripFinder build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  matrix:
    - SDK=iphonesimulator8.1
    - SDK=iphonesimulator8.2
    - SDK=iphonesimulator8.3
    - SDK=iphonesimulator8.4
    - SDK=iphonesimulator9.0
    - SDK=iphonesimulator9.1
    - SDK=iphonesimulator9.2
    - SDK=iphonesimulator9.3
